:imagesdir: ../../assets/images
include::../style.adoc[]

== このワークショップのまとめ

このワークショップを終えることで、{corp}がハイブリッドクラウド環境全体にわたってアプリケーションの接続性、セキュリティ、および可観測性を近代化する上で大きな進歩を遂げるのを支援しました。

OpenShift、Red Hat Service Interconnect、OpenShift Service Mesh、および Red Hat Connectivity Link を活用することで、{corp}は以下を実現できました。

. *Red Hat Service Interconnect でオンプレミスと Cloud ワークロードをブリッジ*
+
{corp}は、OpenShift 上で動作するクラウドベースのサービスを、Red Hat Enterprise Linux (RHEL) 上でホストされているオンプレミスのデータベースに安全に接続しました。Virtual Application Networks と環境変数を使用することで、cars、flights、hotels、insurances などのサービスがレガシーデータにシームレスかつ安全にアクセスできるようになりました。


. *OpenShift Service Mesh でマイクロサービス通信をセキュア化*
+
自動的な sidecar injection と可観測性のための Kiali により、{corp}はサービス間のやり取りに対する可視性と制御を獲得しました。きめ細かいアクセスポリシーにより、discounts のような承認されたサービスのみが承認されたサービスから到達可能であることを保証し、ゼロトラストの原則を強化しました。


. *より安全なリリースのための Progressive Delivery を採用*
+
Canary デプロイメントを使用して、{corp}は discounts サービスの新しいバージョンを段階的にロールアウトし、Kiali で動作とトラフィックを綿密に監視しました。これにより、リスクが軽減され、本番環境での変更に対する信頼性が向上しました。


. *Red Hat Connectivity Link で外部アクセスを簡素化*
+
Platform エンジニアは、DNS、TLS、認証、およびレート制限を備えた安全な Gateway を実装しました。開発者は HTTPRoute を定義し、カスタムポリシーを適用することで、コアシステムを危険にさらすことなく、外部パートナーにサービスを安全に公開しました。


. *Grafana Dashboard でプロアクティブな可観測性を有効化*
+
カスタマイズされた Grafana ダッシュボードは、API パフォーマンス、レイテンシ、およびシステムヘルスに対するリアルタイムの可視性を提供しました。これらの洞察は、運用、開発、およびビジネスチームがアプリケーションスタックを管理および改善するのをサポートしました。


これらの強化により、{corp}はハイブリッド環境全体でより安全かつ効率的に運用できるようになり、成長、イノベーション、および将来の統合に備えることができました。

//TODO
// == Next steps

// You can setup this workshop in your cluster as well. git clone https://github.com/app-connectivity-workshop/acw-ansible and run the Ansible playbook

== リソース

* https://developers.redhat.com/products/service-interconnect/overview[Red Hat Service Interconnect on Red Hat Developers, window=_blank]

* https://kiali.io/[More information about Kiali, window=_blank] | https://docs.redhat.com/en/documentation/red_hat_openshift_service_mesh/3.0/html/observability/kiali-operator-provided-by-red-hat[Kiali Operator provided by Red Hat, window=_blank]

* https://www.redhat.com/en/topics/security/what-is-zero-trust[What is Zero Trust ?, window=_blank]  
